bump python 2.7 --> 3.8 in android script (#164)
The most recent image of Ubuntu 20.04 dropped support for `python2` (googlers see cl/507752630) which was still being used by the script to update android dependencies.
This caused the bot to fail when trying to update Android dependencies.

From the internal [build log](https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fdpebot%2Ffirebase%2Fquickstart-android/activity/f04ac476-f8c9-4a6e-adeb-10544bdde1bc/log):
```bash
virtualenv --python python2.7 env
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python2.7'
```

This should upgrade our script to use python3.8 instead.